### ISSUE TITLE
Status of this project and status of neo.io.NsdfIO

### ISSUE THREAD

**Issue by samuelgarcia** [nsdf/nsdf#48]
Dear nsdf team.

We have in the [neo](https://github.com/NeuralEnsemble/python-neo) project an NsdfIO class that interface the nsdf file and the neo.io API.
The code have been written  by Mieszko Grodzicki @mgr0dzicki.

We are in a process of a strong change in neo see https://github.com/NeuralEnsemble/python-neo/pull/817

Making full change in the neo.NsffIO will represent lot of work.
I would like to make chnages and simplify the IO.
My questions:
  * what is the status of the project ?
  * how many user for the nsdf format ?
  * how many user for the neo.io.NsfIO class ?
  * Can I simpmlify the neo.io.NsfIO class (remove write and remove ChannelIndex) ?

Cheers

Samuel

**Comment by subhacom** [comment]
Sorry I missed your message. I have maintained and updated the NSDF module to some extent for my own use ([this project](https://elifesciences.org/articles/53281) for example). I don't know if @ccluri and the group at Nencki are still using it. I implemented a C++ version in MOOSE (@BhallaLab) several years ago, but not sure if anybody uses it actively.

I have not used neo.io in production, and could not go very far as it was simpler for me to use the nsdf module directly when dumping data from simulations. And for my electrophysiology data, which is saved in a custom format, it is again simpler to read the data directly using numpy rather than trying to fold it into neo API.

I would not worry about write capability as neo seems to focus on electrophysiology and nsdf on simulation data. The only use-case that comes to mind is when someone wants to feed simulated data into a dynamic clamp experiment.
